### ISSUE TITLE
Adding requirements.txt

### ISSUE THREAD

**Issue by mpariente** [hangtingchen/Beam-Guided-TasNet#1]
Hey, 

If you add asteroid and other requirements in a `requirements.txt` files, your repo will appear in the "Useb by" sections of the repos listed under requirements. 

This is good for use (more evidence of use) and for you (more discoverability of your repo from asteroid directly).

Just saying :upside_down_face: 
Cheers !

**Comment by hangtingchen** [comment]
Nice suggestion! We will update this recipe in a few days.
