### ISSUE TITLE
您好我出现这个错误不知道如何解决，向您请教一下！

### ISSUE THREAD

**Issue by zhangxu223** [hangtingchen/Beam-Guided-TasNet#2]
./run.sh --id 0,1,2,3 --stage 3
Results from the following experiment will be stored in exp/train_convtasnet_reverb2reverb_8kmin_e2ff7662
Stage 3: Training
C:\Users\SASPL-1\anaconda3\envs\zx_38\lib\site-packages\asteroid\filterbanks_init_.py:24: VisibleDeprecationWarning: asteroid.filterbanks has been replaced by asteroid_filterbanks and will be totally remove in a future release. Please use asteroid_filterbanks instead.
warnings.warn(
Global seed set to 0
Traceback (most recent call last):
File "train.py", line 137, in
{'data': {'bf_dir': None,
'mode': 'min',
'n_src': 2,
'sample_rate': 8000,
'task': 'reverb2reverb',
'train_dir': 'data/2speakers/wav8k/min/tr',
'valid_dir': 'data/2speakers/wav8k/min/cv'},
'filterbank': {'kernel_size': 16,
'n_channels': 4,
'n_filters': 256,
'stride': 8},
'main_args': {'exp_dir': 'exp/train_convtasnet_reverb2reverb_8kmin_e2ff7662/',
'help': None,
'pretrain': True},
'masknet': {'audio_chan': 4,
'bn_chan': 128,
'causal': False,
'conv_kernel_size': 3,
'hid_chan': 256,
'in_chan': 256,
'mask_act': 'relu',
'n_blocks': 8,
'n_repeats': 3,
'norm_type': 'gLN',
'skip_chan': 128},
'optim': {'lr': 0.001, 'optimizer': 'adam', 'weight_decay': 0.0},
'positional arguments': {},
'training': {'batch_size': 12,
main(arg_dic)
'early_stop': False,
'epochs': 75,
'half_lr': True,
'num_workers': 8}}
Torch MVDR causality: False
Using stft {'n_filters': 4096, 'kernel_size': 4096, 'stride': 1024}
load data from data/2speakers/wav8k/min/tr\mix_reverb.json and ['data/2speakers/wav8k/min/tr\s1_reverb.json', 'data/2speakers/wav8k/min/tr\s2_reverb.json']
Drop 2925 utts(0.26 h) from 20000 (shorter than 32000 samples)
load data from data/2speakers/wav8k/min/cv\mix_reverb.json and ['data/2speakers/wav8k/min/cv\s1_reverb.json', 'data/2speakers/wav8k/min/cv\s2_reverb.json']
Drop 701 utts(0.06 h) from 5000 (shorter than 32000 samples)
File "train.py", line 67, in main
system = BeamTasNetSystem(pretrain=conf['main_args']['pretrain'],
File "D:\ZhangXu\Code\Beam-Guided-TasNet-main\Beam-Guided-TasNet-main\system.py", line 15, ininit
super().init(*args, **kwargs)
File "C:\Users\SASPL-1\anaconda3\envs\zx_38\lib\site-packages\asteroid\engine\system.py", line 61, ininit
self.hparams = Namespace(**self.config_to_hparams(self.config))
File "C:\Users\SASPL-1\anaconda3\envs\zx_38\lib\site-packages\torch\nn\modules\module.py", line 1225, insetattr
object.setattr(self, name, value)
AttributeError: can't set attribute
Stage 4: Training
mv: cannot stat 'exp/train_convtasnet_reverb2reverb_8kmin_e2ff7662/checkpoints': No such file or directory

**Comment by hangtingchen** [comment]
这个bug我没遇到过
建议把self.config_to_hparams(self.config)的结果打印出来看看

**Comment by zhangxu223** [comment]
我觉得会不会是因为我在windows下运行的原因？或者我的torch版本和pytorch-lightning版本不对？能麻烦问一下您安装的这几个包的版本吗

**Comment by zhangxu223** [comment]
解决了谢谢您！就是您说得那行的问题！把问题行改成这句self.save_hyperparameters(self.config_to_hparams(self.config))，就可以了！
