### ISSUE TITLE
16k训练参数

### ISSUE THREAD

**Issue by quancs** [hangtingchen/Beam-Guided-TasNet#4]
您好，请问如果选择16k的数据来进行训练的话，需要修改参数吗 ^-^

**Comment by hangtingchen** [comment]
修改一下
  kernel_size:32 # 2ms
  stride: 16 # 1ms
https://github.com/hangtingchen/Beam-Guided-TasNet/blob/39c7002d4b2c62ccb6a431dc5724f01fa2792f6f/local/net2_noncausal.yml#L5

**Comment by quancs** [comment]
感谢！！
