### ISSUE TITLE
"make_parallel_enc_dec"这个函数在asteroid-filterbanks好像没有了？

### ISSUE THREAD

**Issue by wrz1999** [hangtingchen/Beam-Guided-TasNet#9]
您好，"make_parallel_enc_dec"这个函数在asteroid-filterbanks好像没有了？需要改成什么呢？还是因为asteroid-filterbanks的版本问题呢?

**Comment by hangtingchen** [comment]
this place
https://github.com/hangtingchen/Beam-Guided-TasNet/blob/f0cdd9791ee7a154fb3b4b7593b1bdc65b8554cf/__init_filterbanks__.py#L170
